[package]
name = "ember-sgm-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
futures = "0.3.31"
lazy_static = "1.5.0"
lru-cache = "0.1.2"
lru-cache-macros = "0.3.1"
neo4j_cypher = "0.2.2"
neo4rs = "0.8.0"
rayon = "1.10.0"
sea-orm = "1.1.7"
serde = "1.0.219"
sqlx = "0.8.3"
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.44.1", features = ["full"] }
