[project]
name = "ember-graph-bench-dump"
version = "0.1.0"
description = "Dump benchmark result (JSON format) via matplotlib"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "scienceplots>=2.1.1",
]
